# Generated by Django 3.2.12 on 2022-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_step'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_recipes', to='recipes.Recipe'),
        ),
    ]
