# Generated by Django 4.0.2 on 2022-04-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
