# Generated by Django 3.2.12 on 2022-04-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='diet_restriction',
            field=models.CharField(choices=[('VE', 'Vegetarian'), ('VG', 'Vegan'), ('GF', 'Gluten-Free'), ('NR', 'No Restriction')], default='OT', max_length=2),
        ),
    ]
