# Generated by Django 3.2.12 on 2022-04-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_diet_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='diet_restriction',
            field=models.CharField(choices=[('VE', 'Vegetarian'), ('VG', 'Vegan'), ('GF', 'Gluten-Free'), ('NR', 'No Restriction')], default='NR', max_length=2),
        ),
    ]
