# Generated by Django 3.2.12 on 2022-04-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_diet_restriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='intro',
        ),
    ]
