# Generated by Django 4.0.2 on 2022-04-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_upload'),
        ('recipes', '0010_step'),
    ]

    operations = [
    ]
