# Generated by Django 4.0.2 on 2022-04-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_merge_0010_alter_recipe_upload_0010_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='upload',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
    ]
