# Generated by Django 4.0.2 on 2022-04-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='upload',
            field=models.ImageField(blank=True, default="static 'stock.jpg'", upload_to='media/'),
        ),
    ]
