# Generated by Django 3.2.12 on 2022-04-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='forked_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_forked',
            field=models.IntegerField(default=0),
        ),
    ]
