# Generated by Django 3.2.12 on 2022-04-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20220414_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='forked_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_forked',
        ),
        migrations.AddField(
            model_name='recipe',
            name='forkedid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='isforked',
            field=models.IntegerField(default=0),
        ),
    ]
