# Generated by Django 3.2.12 on 2022-04-16 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20220416_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cook Time (mins)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet_restriction',
            field=models.CharField(choices=[('VE', 'Vegetarian'), ('VG', 'Vegan'), ('GF', 'Gluten-Free'), ('NR', 'No Restriction')], default='NR', max_length=2, verbose_name='Dietary Restriction'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('BR', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner'), ('SN', 'Snack'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Meal Type'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prep Time (mins)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Recipe Title'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='upload',
            field=models.ImageField(blank=True, default="static 'stock.jpg'", upload_to='media/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Step'),
        ),
    ]
