# Generated by Django 3.2.12 on 2022-04-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_ingredient_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='units',
        ),
    ]
