# Generated by Django 3.2.12 on 2022-04-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_remove_ingredient_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
