# Generated by Django 3.2.12 on 2022-04-18 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_ingredient_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='units',
        ),
    ]
