# Generated by Django 3.2.12 on 2022-04-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_remove_ingredient_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(default='', max_length=100, verbose_name='Quantity and Units'),
        ),
    ]
